### ISSUE TITLE
Website / dapp doesn't make it clear that you get WETH not ETH sent to L1 address

### ISSUE THREAD

**Issue by gilescope** [across-protocol/across-frontend#134]
Website / dapp doesn't make it clear that you get WETH not ETH sent to L1 address.

Not a problem unless you decide to send it to an exchange address which is ok because it says it is going to be eth right? We don't like support problems. 

Let's just tell people what they are actually getting so there is no surprises and people want to come back and use it again.

**Comment by dxiy** [comment]
That issue has been previously reported and should be resolved here: https://github.com/across-protocol/across-frontend/pull/120

**Comment by dxiy** [comment]
> Website / dapp doesn't make it clear that you get WETH not ETH sent to L1 address.

Actually as I understood the issue, is that you always get ETH, even though the web UI indicates a wETH transfer to L1 will give you wETH.
