### ISSUE TITLE
Error: Rate model for UMA not found.

### ISSUE THREAD

**Issue by zjuchenyuan** [across-protocol/across-frontend#40]
Console print error when selecting UMA token:
![image](https://user-images.githubusercontent.com/17289004/140857092-f5d94c21-32d5-4c59-a93c-64d583ac1aa6.png)

UMA config should be added to RATE_MODEL:

https://github.com/across-protocol/across-frontend/blob/21de8fd442a75a5a93e8bf1218039595d533cf8f/src/utils/constants.ts#L494-L514

**Comment by mrice32** [comment]
Thank you for reporting this!
